stages:
  data_ingestion:
    cmd: python -m src.pipeline.data_ingestion_pipeline
    deps:
    - src/pipeline/data_ingestion_pipeline.py
    outs:
    - artifacts/data_ingestion/data
  data_transformation:
    cmd: python -m src.pipeline.data_transformation_pipeline
    deps:
    - src/pipeline/data_transformation_pipeline.py
    outs:
    - artifacts/data_transformation/data
  model_trainer:
    cmd: python -m src.pipeline.model_trainer_pipeline
    deps:
    - src/pipeline/model_trainer_pipeline.py
    outs:
    - artifacts/model_trainer/model
  model_evaluation:
    cmd: python -m src.pipeline.model_evaluation_pipeline
    deps:
    - src/pipeline/model_evaluation_pipeline.py
    outs:
    - artifacts/model_evaluation/metrics.json