artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_file: data/bank_subscription.xlsx
  save_file: artifacts/data_ingestion/data

data_transformation:
  root_dir: artifacts/data_transformation
  data_file: artifacts/data_ingestion/data/data.csv
  save_file: artifacts/data_transformation/data
  train_dir: artifacts/data_transformation/data
  test_dir: artifacts/data_transformation/data

model_trainer:
  root_dir: artifacts/model_trainer
  data_file: artifacts/data_transformation/data/processed_data.csv
  train_dir: artifacts/data_transformation/data/train.csv
  test_dir: artifacts/data_transformation/data/test.csv
  model_save_dir: artifacts/model_trainer/model/model.pkl