artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  data_file: data/bank_subscription.xlsx
  save_file: artifacts/data_ingestion/data

data_transformation:
  root_dir: artifacts/data_transformation
  data_file: artifacts/data_ingestion/data/data.csv
  save_file: artifacts/data_transformation/data